import { describe, expect, it } from "vitest";
import { requirementsIsLockGrade } from "./python-loose.js";

// Loose-manifest detection for Python (ADR 0006c, laimk-hse.5). A Python repo is
// LOOSE — resolved by the single resolving install and surfaced as unpinned — when its
// declared deps are not lock-grade:
//   - an unpinned (no `==`) or hash-less requirements.txt (the common case), or
//   - an abstract pyproject.toml with no requirements.txt and no lock.
// `requirementsIsLockGrade` is the pure predicate the loose check derives from:
// requirements.txt is lock-grade ONLY when every requirement line is `==`-pinned
// AND carries at least one `--hash=` (pip's hash-checking contract).

describe("requirementsIsLockGrade (the pure lock-grade predicate — ADR 0006c)", () => {
  it("treats a fully ==-pinned, --hash-bearing requirements.txt as lock-grade", () => {
    const text =
      "idna==3.10 \\\n" +
      "    --hash=sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3\n" +
      "urllib3==2.2.3 \\\n" +
      "    --hash=sha256:ca899ca043dcb1bafa3e262d73aa25c465bfb49e0bd9dd5d59f1d0acba2f8fac\n";
    expect(requirementsIsLockGrade(text)).toBe(true);
  });

  it("is NOT lock-grade when a requirement is unpinned (no ==)", () => {
    // The poster child: a hand-written requirements.txt with bare package names.
    expect(requirementsIsLockGrade("idna\nurllib3\n")).toBe(false);
  });

  it("is NOT lock-grade when a pinned requirement carries no --hash", () => {
    // Pinned-without-hashes is not a stable lock: lock-grade requires hashes.
    expect(requirementsIsLockGrade("idna==3.10\nurllib3==2.2.3\n")).toBe(false);
  });

  it("is NOT lock-grade when only SOME requirements are hash-pinned (mixed)", () => {
    const text =
      "idna==3.10 \\\n" +
      "    --hash=sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3\n" +
      "urllib3==2.2.3\n";
    expect(requirementsIsLockGrade(text)).toBe(false);
  });

  it("is NOT lock-grade for a loose constraint (>=) even with a hash", () => {
    expect(requirementsIsLockGrade("urllib3>=2.0 --hash=sha256:abc\n")).toBe(false);
  });

  it("ignores comments, blank lines, and pip option lines when judging lock-grade", () => {
    const text =
      "# autogenerated by uv\n" +
      "\n" +
      "--index-url https://pypi.org/simple\n" +
      "idna==3.10 --hash=sha256:946d195a0d259cbba61165e88e65941f16e9b36ea6ddb97f00452bae8b1287d3\n";
    expect(requirementsIsLockGrade(text)).toBe(true);
  });

  it("is NOT lock-grade for an empty/whitespace requirements.txt (nothing pins it)", () => {
    // An empty requirements.txt declares nothing concrete — treat it as not yet
    // lock-grade so a real manifest (pyproject) drives the resolve.
    expect(requirementsIsLockGrade("")).toBe(false);
    expect(requirementsIsLockGrade("   \n# only a comment\n")).toBe(false);
  });

  it("is conservative (not lock-grade) for undefined text", () => {
    expect(requirementsIsLockGrade(undefined)).toBe(false);
  });
});
