import type { ToolchainBuild, ToolchainContext } from "./types.js";

/**
 * The per-Ecosystem Toolchain Nix expressions (ADR 0001/0012). dustcastle realizes
 * ONLY the Toolchain into the shared Store — Project Deps install in-Sandbox via the
 * sandcastle hook (ADR 0012, always-impure), so there is NO deps FOD / Importer here
 * (those `src/nix/*` generators were deleted). Each generator emits one derivation —
 * the language Toolchain, resolved from nixpkgs — under a single named attr the store
 * builds with `nix-build -A <attr>`. nixpkgs is pinned via `fetchTarball` only (ADR
 * 0001: no external flake inputs).
 */

/** The pinned nixpkgs `let` binding shared by every Toolchain expression. */
const NIXPKGS_PREAMBLE = `  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };`;

/** Node's Toolchain: nixpkgs' `nodejs`, as its own Store path. */
export function generateNodeToolchain(ctx: ToolchainContext): ToolchainBuild {
  const expression = `# Generated by dustcastle — Node Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";       # cosmetic; the store sanitizes/labels the build dir
  nodejs = pkgs.nodejs;          # the Toolchain, as its own store path
}
`;
  return { expression, attr: "nodejs" };
}

/** Go's Toolchain: nixpkgs' `go`, as its own Store path. */
export function generateGoToolchain(ctx: ToolchainContext): ToolchainBuild {
  const expression = `# Generated by dustcastle — Go Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";
  go = pkgs.go;                 # the Toolchain, as its own store path
}
`;
  return { expression, attr: "go" };
}

/**
 * Python's Toolchain: the resolved interpreter with pip + pytest, as its own Store
 * path. The Toolchain ships pip (the in-Sandbox install uses it) and pytest (the
 * test gate) from nixpkgs. The resolved nixpkgs interpreter attr (`python311`/…,
 * ADR 0006b) is threaded via `toolchainVersion`; defaults to `python312`.
 */
export function generatePythonToolchain(ctx: ToolchainContext): ToolchainBuild {
  const interpreter = ctx.toolchainVersion ?? "python312";
  const expression = `# Generated by dustcastle — Python Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
  python = pkgs.${interpreter};                 # the Toolchain (resolved version), as its own store path
in {
  pname = "${ctx.pname}";
  # The Toolchain ships pip (to install Project Deps in-Sandbox) and pytest (the
  # test gate runner) from nixpkgs — Project Deps themselves come from the install.
  python = python.withPackages (ps: [ ps.pip ps.pytest ]);
}
`;
  return { expression, attr: "python" };
}

/** Rust's Toolchain: rustc + cargo + a C compiler, joined into one Store path. */
export function generateRustToolchain(ctx: ToolchainContext): ToolchainBuild {
  const expression = `# Generated by dustcastle — Rust Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";
  toolchain = pkgs.symlinkJoin {
    name = "rust-toolchain";
    paths = [ pkgs.rustc pkgs.cargo pkgs.cc ];   # the Toolchain, as one store path
  };
}
`;
  return { expression, attr: "toolchain" };
}
