import type { ToolchainBuild, ToolchainContext } from "./types.js";

/**
 * The per-Ecosystem Toolchain Nix expressions (ADR 0001/0012). dustcastle realizes
 * ONLY the Toolchain into the shared Store — Project Deps install in-Sandbox via the
 * sandcastle hook (ADR 0012, always-impure), so there is NO deps FOD / Importer here
 * (those `src/nix/*` generators were deleted). Each generator emits one derivation —
 * the language Toolchain, resolved from nixpkgs — under a single named attr the store
 * builds with `nix-build -A <attr>`. nixpkgs is pinned via `fetchTarball` only (ADR
 * 0001: no external flake inputs).
 */

/** The pinned nixpkgs `let` binding shared by every Toolchain expression. */
const NIXPKGS_PREAMBLE = `  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };`;

/**
 * Node's Toolchain: nixpkgs' `nodejs` plus the detected manager's CLI, joined into one
 * Store path. The in-Sandbox install runs the real Package Manager (ADR 0012), so a
 * pnpm/yarn/bun repo's Toolchain must carry that CLI on PATH — only npm ships with
 * nodejs, so npm needs nothing extra (no store bloat). Mirrors the Python Toolchain's
 * uv/poetry handling.
 */
export function generateNodeToolchain(ctx: ToolchainContext): ToolchainBuild {
  // The manager CLI the in-Sandbox install needs on PATH (ADR 0012). npm ships with
  // nodejs → no extra tool; pnpm/yarn/bun are their own nixpkgs packages.
  const managerTool =
    ctx.packageManager === "pnpm"
      ? "pkgs.pnpm"
      : ctx.packageManager === "yarn"
        ? "pkgs.yarn"
        : ctx.packageManager === "bun"
          ? "pkgs.bun"
          : undefined;
  const paths = ["pkgs.nodejs", ...(managerTool !== undefined ? [managerTool] : [])].join(" ");
  const expression = `# Generated by dustcastle — Node Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";       # cosmetic; the store sanitizes/labels the build dir
  # nodejs (ships npm) + the detected manager's CLI (pnpm/yarn/bun) on one PATH so the
  # in-Sandbox install resolves.
  toolchain = pkgs.symlinkJoin { name = "node-toolchain"; paths = [ ${paths} ]; };
}
`;
  return { expression, attr: "toolchain" };
}

/** Go's Toolchain: nixpkgs' `go`, as its own Store path. */
export function generateGoToolchain(ctx: ToolchainContext): ToolchainBuild {
  const expression = `# Generated by dustcastle — Go Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";
  go = pkgs.go;                 # the Toolchain, as its own store path
}
`;
  return { expression, attr: "go" };
}

/**
 * Python's Toolchain: the resolved interpreter with pip + pytest, plus the detected
 * manager's in-Sandbox EXPORT tool, joined into one Store path. The Toolchain ships pip
 * (the in-Sandbox install uses it) and pytest (the test gate) from nixpkgs. uv/poetry
 * run their `export` front-end IN-SANDBOX now (ADR 0012), so a uv repo's Toolchain must
 * carry `uv` and a poetry repo's `poetry` — pip consumes requirements.txt directly and
 * needs neither, so it gets no extra tool (no store bloat). The resolved nixpkgs
 * interpreter attr (`python311`/…, ADR 0006b) is threaded via `toolchainVersion`;
 * defaults to `python312`.
 */
export function generatePythonToolchain(ctx: ToolchainContext): ToolchainBuild {
  const interpreter = ctx.toolchainVersion ?? "python312";
  // The in-Sandbox export front-end the detected manager needs on PATH (ADR 0012). pip
  // reads requirements.txt directly → no extra tool; uv/poetry must run their export.
  const exportTool = ctx.packageManager === "uv" ? "pkgs.uv" : ctx.packageManager === "poetry" ? "pkgs.poetry" : undefined;
  const paths = ["pythonEnv", ...(exportTool !== undefined ? [exportTool] : [])].join(" ");
  const expression = `# Generated by dustcastle — Python Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
  python = pkgs.${interpreter};                 # the Toolchain (resolved version), as its own store path
  # pip (to install Project Deps in-Sandbox) + pytest (the test gate runner) from nixpkgs.
  pythonEnv = python.withPackages (ps: [ ps.pip ps.pytest ]);
in {
  pname = "${ctx.pname}";
  # Join the interpreter env with the detected manager's export tool (uv/poetry) — both
  # on one PATH so the in-Sandbox install's export step + pip install resolve.
  toolchain = pkgs.symlinkJoin { name = "python-toolchain"; paths = [ ${paths} ]; };
}
`;
  return { expression, attr: "toolchain" };
}

/** Rust's Toolchain: rustc + cargo + a C compiler, joined into one Store path. */
export function generateRustToolchain(ctx: ToolchainContext): ToolchainBuild {
  const expression = `# Generated by dustcastle — Rust Toolchain (ADR 0001/0012).
# Toolchain ONLY: Project Deps install in-Sandbox via the sandcastle hook (no FOD).
let
${NIXPKGS_PREAMBLE}
in {
  pname = "${ctx.pname}";
  toolchain = pkgs.symlinkJoin {
    name = "rust-toolchain";
    # rustc + cargo + the stdenv C compiler wrapper (provides cc, the linker driver
    # cargo invokes). pkgs.cc does not exist in nixpkgs — the wrapper is stdenv.cc.
    paths = [ pkgs.rustc pkgs.cargo pkgs.stdenv.cc ];   # the Toolchain, as one store path
  };
}
`;
  return { expression, attr: "toolchain" };
}
