/** A buildable Nix expression plus the attribute names the store will realize. */
export interface NixBuild {
  /** The Nix expression (a `default.nix` body). */
  readonly expression: string;
  /** Attribute paths to realize via `nix-build -A <attr>`. */
  readonly attrs: {
    /** The language Toolchain store path (CONTEXT.md: Toolchain). */
    readonly toolchain: string;
    /** The Project Deps store path (the vendored modules). */
    readonly deps: string;
    /** The built app (also runs the offline `go test` gate via doCheck). */
    readonly app: string;
  };
}

export interface GoBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published module. */
  readonly version?: string;
  /**
   * The fixed-output hash pinning the vendored modules (ADR 0004). A wrong hash
   * fails the build, so the lockfile is genuinely enforced. Discovered by the
   * store via a first build when unknown.
   */
  readonly vendorHash: string;
  /**
   * The Nix `src` path the build runs against. Defaults to the directory the
   * expression is evaluated in (the store stages the project source there).
   */
  readonly src?: string;
}

/**
 * Generate the Go importer expression (ADR 0004): `buildGoModule` splits into a
 * fixed-output vendor derivation (hash-pinned modules, the one network step)
 * and an offline build/test, landing the Toolchain and Project Deps as separate
 * content-addressed Store paths. Ported from the proven Go spike.
 */
export function generateGoBuild(spec: GoBuildSpec): NixBuild {
  const version = spec.version ?? "0.0.0";
  const src = spec.src ?? "./.";

  const expression = `# Generated by dustcastle — Go importer (ADR 0004).
# buildGoModule: a fixed-output vendor FOD (hash-pinned) + an offline build/test.
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  app = pkgs.buildGoModule {
    pname = "${spec.pname}";
    version = "${version}";
    src = ${src};
    vendorHash = "${spec.vendorHash}";
    # doCheck defaults true -> \`go test ./...\` runs in the offline Nix sandbox.
  };
in {
  inherit app;
  go = pkgs.go;                 # the Toolchain, as its own store path
  deps = app.goModules;         # Project Deps: vendored modules, one store path
  default = app;
}
`;

  return { expression, attrs: { toolchain: "go", deps: "deps", app: "app" } };
}
