import type { NixBuild } from "./go.js";

export type { NixBuild } from "./go.js";

export interface NodeBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published app. */
  readonly version?: string;
  /**
   * The fixed-output hash pinning the fetched npm cache (ADR 0004). A wrong hash
   * fails the build, so the lockfile is genuinely enforced. Discovered by the
   * store via a first build when unknown (same mechanism as Go's vendorHash).
   */
  readonly npmDepsHash: string;
  /** The Nix `src` path the build runs against. Defaults to `./src` (staged). */
  readonly src?: string;
}

/**
 * Generate the Node importer expression (ADR 0004). `buildNpmPackage` fixed-
 * output-fetches every lockfile dependency (hash-pinned by `npmDepsHash`, the
 * one network step) into the Store, then runs **real `npm ci --offline`** against
 * that cache to assemble `node_modules` — actual npm, no network.
 *
 * Crucially the provision build runs with `--ignore-scripts`: it never executes
 * untrusted `postinstall`/`preinstall` code. Pure, offline assembly only. When a
 * dep genuinely needs an install script, that's "impurity needed" (detected from
 * the lockfile) and is handled by the policy + the container, not here — so
 * nix-portable's lack of an enforced no-network build sandbox can't be abused.
 *
 * Same `NixBuild { expression, attrs }` contract as the Go importer: the `deps`
 * attr realizes the assembled `node_modules` as its own Store path, which the
 * Sandbox stages in (the Node analogue of Go's vendored modules).
 */
export function generateNodeBuild(spec: NodeBuildSpec): NixBuild {
  const version = spec.version ?? "0.0.0";
  const src = spec.src ?? "./src";

  const expression = `# Generated by dustcastle — Node importer (ADR 0004).
# buildNpmPackage: a fixed-output npm-deps FOD (hash-pinned) + an offline,
# scripts-ignored \`npm ci\` that assembles node_modules into the Store.
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  nodejs = pkgs.nodejs;          # the Toolchain, as its own store path
  # node_modules assembled offline from the hash-pinned npm cache. We override
  # installPhase to publish node_modules itself (the Project Deps store path).
  deps = pkgs.buildNpmPackage {
    pname = "${spec.pname}-deps";
    version = "${version}";
    src = ${src};
    npmDepsHash = "${spec.npmDepsHash}";
    dontNpmBuild = true;
    # PURE: never run untrusted lifecycle scripts during provisioning.
    npmInstallFlags = [ "--ignore-scripts" ];
    npmFlags = [ "--ignore-scripts" ];
    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      cp -R node_modules "$out/node_modules"
      runHook postInstall
    '';
  };
in {
  inherit nodejs deps;
  app = deps;                    # provision proves offline assembly; the test
                                 # gate runs in the container (ADR 0003).
}
`;

  return { expression, attrs: { toolchain: "nodejs", deps: "deps", app: "app" } };
}
