import type { NixBuild } from "./go.js";

export type { NixBuild } from "./go.js";

export interface PnpmBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published app. */
  readonly version?: string;
  /**
   * The fixed-output hash pinning the fetched pnpm store (ADR 0004). A wrong hash
   * fails the build, so the lockfile is genuinely enforced. Discovered by the
   * store via a first build when unknown (same mechanism as Go's vendorHash).
   */
  readonly depsHash: string;
  /** The Nix `src` path the build runs against. Defaults to `./src` (staged). */
  readonly src?: string;
}

/**
 * Generate the pnpm importer expression (ADR 0004) — slice 2b. The nixpkgs
 * `fetchPnpmDeps` fixed-output-fetches the whole pnpm content-addressed store
 * (hash-pinned by `depsHash`, the one network step) into the Store, then
 * `pnpmConfigHook` runs a **real, offline `pnpm install`** against that store to
 * assemble `node_modules` — actual pnpm, no network. `fetcherVersion = 3` pins
 * the store layout so the hash stays reproducible across pnpm point releases.
 *
 * Crucially the provision install runs with `--ignore-scripts` (via
 * `pnpmInstallFlags`): it never executes untrusted `postinstall`/`preinstall`
 * code. Pure, offline assembly only. When a dep genuinely needs an install
 * script, that's "impurity needed" and is handled by the policy + the container,
 * not here — so nix-portable's lack of an enforced no-network build sandbox can't
 * be abused.
 *
 * Same `NixBuild { expression, attrs }` contract — and the same `nodejs`/`deps`/
 * `app` attribute names — as the npm importer, so the store dispatches it through
 * the shared JS provision path and the plan stages `<deps>/node_modules`
 * identically.
 */
export function generatePnpmBuild(spec: PnpmBuildSpec): NixBuild {
  const version = spec.version ?? "0.0.0";
  const src = spec.src ?? "./src";

  const expression = `# Generated by dustcastle — pnpm importer (ADR 0004).
# fetchPnpmDeps: a fixed-output pnpm-store FOD (hash-pinned) + an offline,
# scripts-ignored \`pnpm install\` (pnpmConfigHook) that assembles node_modules
# into the Store.
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  nodejs = pkgs.nodejs;          # the Toolchain, as its own store path
  # pnpm pinned to a major version: the content-addressed store format changes
  # between majors, so an unpinned pnpm would invalidate depsHash (ADR 0004).
  pnpm = pkgs.pnpm;
  # node_modules assembled offline from the hash-pinned pnpm store. The install
  # phase publishes node_modules itself (the Project Deps store path).
  deps = pkgs.stdenv.mkDerivation (finalAttrs: {
    pname = "${spec.pname}-deps";
    version = "${version}";
    src = ${src};
    nativeBuildInputs = [ nodejs pnpm pkgs.pnpmConfigHook ];
    pnpmDeps = pkgs.fetchPnpmDeps {
      inherit (finalAttrs) pname version src;
      inherit pnpm;
      fetcherVersion = 3;
      hash = "${spec.depsHash}";
    };
    # PURE: never run untrusted lifecycle scripts during provisioning. The
    # offline \`pnpm install\` (pnpmConfigHook) reads this flag.
    pnpmInstallFlags = [ "--ignore-scripts" ];
    dontBuild = true;
    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      cp -R node_modules "$out/node_modules"
      runHook postInstall
    '';
  });
in {
  inherit nodejs deps;
  app = deps;                    # provision proves offline assembly; the test
                                 # gate runs in the container (ADR 0003).
}
`;

  return { expression, attrs: { toolchain: "nodejs", deps: "deps", app: "app" } };
}
