import type { NixBuild } from "./go.js";

export type { NixBuild } from "./go.js";

export interface PythonBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published app. */
  readonly version?: string;
  /**
   * The fixed-output hash pinning the downloaded wheelhouse (ADR 0004/0006a). The
   * pip-FOD has ONE aggregate output hash, discovered by the store via a first
   * build when unknown (same mechanism as Go's vendorHash / Node's npmDepsHash).
   */
  readonly pythonDepsHash: string;
  /** The Nix `src` path the build runs against. Defaults to `./src` (staged). */
  readonly src?: string;
}

/**
 * Generate the Python pip-FOD Importer expression (ADR 0006 amendment). The
 * Python Importer is a single pip fixed-output derivation — the direct
 * `fetchNpmDeps` analogue — NOT uv2nix/poetry2nix (those are external flake
 * inputs, which would break the nixpkgs-via-`fetchTarball`-only invariant).
 *
 * Two derivations, mirroring node.ts:
 *   1. `pipDeps` — a network-ON fixed-output derivation that runs
 *      `pip download --only-binary=:all: --require-hashes` into a wheelhouse
 *      (the one network step, hash-pinned by `pythonDepsHash`). `--only-binary`
 *      forbids any build during download (wheels only, deterministic), and the
 *      lockfile's own hashes are honoured via `--require-hashes`.
 *   2. `deps` — a network-ISOLATED step that runs `pip install --no-index
 *      --find-links` against that wheelhouse to assemble the Project Deps offline.
 *      Wheels run no install-time code, so assembly is pure by construction.
 *
 * Same `NixBuild { expression, attrs }` contract as the Go/Node Importers: the
 * `deps` attr realizes the assembled site-packages as its own Store path, which
 * the Sandbox stages in. The live build is proven by the gated Python e2e.
 */
export function generatePythonBuild(spec: PythonBuildSpec): NixBuild {
  const version = spec.version ?? "0.0.0";
  const src = spec.src ?? "./src";

  const expression = `# Generated by dustcastle — Python pip-FOD Importer (ADR 0006 amendment).
# A network-ON wheelhouse FOD (hash-pinned) + an offline \`pip install --no-index\`
# that assembles site-packages into the Store. Wheels run no install-time code.
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  python = pkgs.python312;                 # the Toolchain, as its own store path
  # The Toolchain ships pip (to assemble Project Deps) and pytest (the offline test
  # gate runner) from nixpkgs — never the network. Project Deps come from the FOD.
  pyWithPip = python.withPackages (ps: [ ps.pip ps.pytest ]);
  reqs = ${src}/requirements.txt;

  # (1) FOD: network ON, ONE aggregate hash (discovered via fake -> mismatch -> real).
  #     --only-binary=:all: forbids any build during download (wheels only,
  #     deterministic); --require-hashes honours the lockfile's own hashes.
  pipDeps = pkgs.stdenv.mkDerivation {
    pname = "${spec.pname}-pip-deps";
    version = "${version}";
    dontUnpack = true;
    nativeBuildInputs = [ pyWithPip pkgs.cacert ];
    installPhase = ''
      export HOME=$TMPDIR
      mkdir -p "$out"
      python -m pip download \\
        --no-cache-dir --only-binary=:all: --require-hashes \\
        -r \${reqs} -d "$out"
    '';
    outputHashMode = "recursive";
    outputHashAlgo = "sha256";
    outputHash = "${spec.pythonDepsHash}";
  };

  # (2) PURE offline assembly: NO network, only the FOD wheelhouse. Wheels run no
  #     code, so this never executes untrusted install-time code.
  deps = pkgs.stdenv.mkDerivation {
    pname = "${spec.pname}-deps";
    version = "${version}";
    dontUnpack = true;
    nativeBuildInputs = [ pyWithPip ];
    installPhase = ''
      export HOME=$TMPDIR
      mkdir -p "$out/site"
      python -m pip install \\
        --no-index --find-links=\${pipDeps} --only-binary=:all: --require-hashes \\
        -r \${reqs} --target="$out/site"
    '';
  };
in {
  inherit deps;
  python = pyWithPip;            # the Toolchain (with pip), as its own store path
  app = deps;                    # provision proves offline assembly; the test
                                 # gate runs in the container (ADR 0003).
}
`;

  return { expression, attrs: { toolchain: "python", deps: "deps", app: "app" } };
}
