import type { NixBuild } from "./go.js";

export type { NixBuild } from "./go.js";

/** Shared basename for Rust's staged CARGO_HOME (Importer + Sandbox agreement). */
export const CARGO_HOME_BASENAME = "dustcastle-cargo-home";

export interface RustBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published crate. */
  readonly version?: string;
  /** The fixed-output hash pinning Cargo's vendored dependency tree. */
  readonly cargoHash: string;
  /** The Nix `src` path the build runs against. Defaults to `./src` (staged). */
  readonly src?: string;
}

/**
 * Generate the Rust/Cargo importer expression (dustcastle-gy5.2). Cargo deps are
 * fetched once via `fetchCargoVendor` under a single aggregate `cargoHash`, then
 * assembled into a relocatable deps directory whose config is staged into
 * `$CARGO_HOME` by the existing env-only Sandbox path.
 */
export function generateRustBuild(spec: RustBuildSpec): NixBuild {
  const version = spec.version ?? "0.1.0";
  const src = spec.src ?? "./src";

  const expression = `# Generated by dustcastle — Rust/Cargo importer (dustcastle-gy5.2).
# fetchCargoVendor: a fixed-output Cargo vendor FOD (hash-pinned) + an offline
# cargo test gate using a relocatable CARGO_HOME staged from the Store.
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  src = ${src};
  cargoHash = "${spec.cargoHash}";
  # (1) Network-ON FOD: one aggregate cargoHash, discovered by dustcastle's
  # existing fake-hash → mismatch → real-hash loop when unknown.
  cargoVendor = pkgs.rustPlatform.fetchCargoVendor {
    inherit src;
    name = "${spec.pname}-${version}-cargo-vendor";
    hash = cargoHash;
  };

  # (2) Relocatable deps dir. Cargo resolves a config-relative source directory
  # against the GRANDPARENT of config.toml, so rebase @vendor@ to the CARGO_HOME
  # basename: parent($CARGO_HOME)/${CARGO_HOME_BASENAME}/vendor == $CARGO_HOME/vendor.
  cargoDeps = pkgs.runCommand "${spec.pname}-${version}-cargo-deps" { } ''
    mkdir -p "$out"
    cp -RL \${cargoVendor} "$out/vendor"
    chmod -R u+w "$out"
    if [ -f "$out/vendor/.cargo/config.toml" ]; then
      sed "s|@vendor@|${CARGO_HOME_BASENAME}/vendor|g" \
        "$out/vendor/.cargo/config.toml" > "$out/config.toml"
    else
      cat > "$out/config.toml" <<'EOF'
[source.crates-io]
replace-with = "vendored-sources"
[source.vendored-sources]
directory = "${CARGO_HOME_BASENAME}/vendor"
EOF
    fi
  '';

  toolchain = pkgs.symlinkJoin {
    name = "rust-toolchain";
    paths = [ pkgs.rustc pkgs.cargo pkgs.cc ];
  };

  # (3) Offline build+test gate. This mirrors Sandbox staging: copy the deps Store
  # path into a writable CARGO_HOME with the agreed basename, then force offline.
  app = pkgs.stdenv.mkDerivation {
    pname = "${spec.pname}";
    version = "${version}";
    inherit src;
    nativeBuildInputs = [ pkgs.rustc pkgs.cargo pkgs.cc ];
    buildPhase = ''
      runHook preBuild
      export CARGO_HOME="$TMPDIR/${CARGO_HOME_BASENAME}"
      rm -rf "$CARGO_HOME"
      cp -RL \${cargoDeps} "$CARGO_HOME"
      chmod -R u+w "$CARGO_HOME"
      export CARGO_NET_OFFLINE=true
      cargo test --offline --frozen
      runHook postBuild
    '';
    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      cp -R target "$out/target" 2>/dev/null || true
      runHook postInstall
    '';
  };
in {
  inherit toolchain cargoDeps app;
  deps = cargoDeps;              # Project Deps: staged CARGO_HOME contents
  default = app;
}
`;

  return { expression, attrs: { toolchain: "toolchain", deps: "deps", app: "app" } };
}
