import type { NixBuild } from "./go.js";

export type { NixBuild } from "./go.js";

export interface YarnBuildSpec {
  /** Derivation name (typically the repo directory name). */
  readonly pname: string;
  /** Derivation version; cosmetic for a non-published app. */
  readonly version?: string;
  /**
   * The fixed-output hash pinning the fetched yarn offline cache (ADR 0004). A
   * wrong hash fails the build, so the lockfile is genuinely enforced. Discovered
   * by the store via a first build when unknown (same mechanism as Go's vendorHash).
   */
  readonly depsHash: string;
  /** The Nix `src` path the build runs against. Defaults to `./src` (staged). */
  readonly src?: string;
}

/**
 * Generate the yarn importer expression (ADR 0004) — slice 2b, targeting Yarn v1
 * (classic `yarn.lock`). The nixpkgs `fetchYarnDeps` fixed-output-fetches the
 * offline cache from the lockfile (hash-pinned by `depsHash`, the one network
 * step) into the Store, then `yarnConfigHook` runs a **real, offline `yarn
 * install`** against that cache to assemble `node_modules` — actual yarn, no
 * network.
 *
 * Purity here is structural: only `yarnConfigHook` runs, and it just populates
 * `node_modules` from the offline cache. Package build/lifecycle scripts run in
 * `yarnBuildHook`, which we deliberately omit — so no untrusted `postinstall`
 * code executes during provisioning. When a dep genuinely needs an install
 * script, that's "impurity needed" and is handled by the policy + the container,
 * not here.
 *
 * Same `NixBuild { expression, attrs }` contract — and the same `nodejs`/`deps`/
 * `app` attribute names — as the npm/pnpm importers, so the store dispatches it
 * through the shared JS provision path and the plan stages `<deps>/node_modules`
 * identically.
 */
export function generateYarnBuild(spec: YarnBuildSpec): NixBuild {
  const version = spec.version ?? "0.0.0";
  const src = spec.src ?? "./src";

  const expression = `# Generated by dustcastle — yarn importer (ADR 0004), Yarn v1.
# fetchYarnDeps: a fixed-output offline-cache FOD (hash-pinned by yarn.lock) +
# an offline \`yarn install\` (yarnConfigHook) that assembles node_modules into
# the Store. Only the config hook runs -> no package lifecycle scripts (pure).
let
  nixpkgs = builtins.fetchTarball
    "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz";
  pkgs = import nixpkgs { };
  nodejs = pkgs.nodejs;          # the Toolchain, as its own store path
  # node_modules assembled offline from the hash-pinned yarn offline cache. The
  # install phase publishes node_modules itself (the Project Deps store path).
  deps = pkgs.stdenv.mkDerivation (finalAttrs: {
    pname = "${spec.pname}-deps";
    version = "${version}";
    src = ${src};
    nativeBuildInputs = [ nodejs pkgs.yarnConfigHook ];
    yarnOfflineCache = pkgs.fetchYarnDeps {
      yarnLock = finalAttrs.src + "/yarn.lock";
      hash = "${spec.depsHash}";
    };
    dontBuild = true;
    installPhase = ''
      runHook preInstall
      mkdir -p "$out"
      cp -R node_modules "$out/node_modules"
      runHook postInstall
    '';
  });
in {
  inherit nodejs deps;
  app = deps;                    # provision proves offline assembly; the test
                                 # gate runs in the container (ADR 0003).
}
`;

  return { expression, attrs: { toolchain: "nodejs", deps: "deps", app: "app" } };
}
